version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: to-do-list
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
